spring:
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: foo
      auto-offset-reset: earliest
      enable-auto-commit: false
    producer:
      bootstrap-servers: localhost:9092
      acks: all
      retries: 1
      properties:
        retry:
          backoff:
            ms: 100
        delivery:
          timeout:
            ms: 120000
    listener:
      ack-mode: record

server:
  port: 7080
  tomcat:
    connection-timeout: 30000
    threads:
      max: 512
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true
